package com.seu.magicfilter.utils;

/**
 * Created by why8222 on 2016/2/25.
 */
public enum  MagicFilterType {
    NONE,
    FAIRYTALE,//童真
    SUNRISE,//阳光
    SUNSET,//日落
    WHITECAT,//白光
    BLACKCAT,//黑光
    SKINWHITEN,//缎光白
    BEAUTY,//美肤
    HEALTHY,//健康
    SWEETS,//甜美
    ROMANCE,//浪漫
    SAKURA,//樱花
    WARM,//暖光
    ANTIQUE,//复古
    NOSTALGIA,//怀旧
    CALM,//丰饶
    LATTE,//拿铁风
    TENDER,//温柔
    COOL,//酷
    EMERALD,//
    EVERGREEN,
    CRAYON,
    SKETCH,
    AMARO,
    BRANNAN,
    BROOKLYN,
    EARLYBIRD,
    FREUD,
    HEFE,
    HUDSON,
    INKWELL,
    KEVIN,
    LOCKUP,
    LOMO,
    N1977,
    NASHVILLE,
    PIXAR,
    RISE,
    SIERRA,
    SUTRO,
    TOASTER2,
    VALENCIA,
    WALDEN,
    XPROII,
    //image adjust
    CONTRAST,//对比度
    BRIGHTNESS,//亮度
    EXPOSURE,//曝光
    HUE,//彩色
    SATURATION,//饱和度
    SHARPEN,//尖锐
    IMAGE_ADJUST//调整
}
